### ISSUE TITLE
Name and URL of archive

### ISSUE THREAD

**Issue by jollysea** [quicoto/mastodon-archive#2]
Hello, same thing as with the other issue: I recognize this is more or less a private project, so don't feel obliged to change anything but I haven't found another project that does what I wanted to (convert the archive of an old, no-long-offline instance into html) so I guess there might be some other people wanting to use this.

It seems the default output html file has your name and instance URL, and I had not seen a warning or information about this. Of course it's easy to replace these things in the output, but a possbility to do this beforehand would be cool for people wanting to use this on their own. 

Also, since the instance where I pulled the archive from is no longer offline, I had to replace the path for the images. Again, not a big issue, but an option to use a local archive would be really cool.

**Comment by quicoto** [comment]
Makes sense. I have tweaked the code to pull the name of the person from the archive, as well as the URL 

What I didn't know how to do is the Media URL. Maybe there's a way to pass an argument/parameter?

See the changes here https://github.com/quicoto/mastodon-archive/commit/9bb3cb9e58525e8c27c6d273c9dd57f7cfcb71a5

**Comment by alech** [comment]
I have a pull request out to pass in the Media URL: #3

**Comment by quicoto** [comment]
#3  has been merged
